<?php


/**
 * This class defines the structure of the 'vehicxorden' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 07/28/10 15:21:16
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class VehicxordenTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.VehicxordenTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('vehicxorden');
		$this->setPhpName('Vehicxorden');
		$this->setClassname('Vehicxorden');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('IDORDEN', 'Idorden', 'INTEGER', true, null, null);
		$this->addForeignKey('IDVEHICULO', 'Idvehiculo', 'INTEGER', 'vehiculo', 'ID', true, null, null);
		$this->addColumn('HORADESDE', 'Horadesde', 'TIMESTAMP', true, null, null);
		$this->addColumn('HORAHASTA', 'Horahasta', 'TIMESTAMP', false, null, null);
		$this->addColumn('CANTPASAJEROS', 'Cantpasajeros', 'INTEGER', false, null, null);
		$this->addForeignKey('CHOFER', 'Chofer', 'INTEGER', 'chofer', 'ID', false, null, null);
		$this->addForeignKey('PROVEEDOR', 'Proveedor', 'INTEGER', 'proveedor', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Vehiculo', 'Vehiculo', RelationMap::MANY_TO_ONE, array('idVehiculo' => 'id', ), null, null);
    $this->addRelation('ChoferRelatedByChofer', 'Chofer', RelationMap::MANY_TO_ONE, array('chofer' => 'id', ), null, null);
    $this->addRelation('ProveedorRelatedByProveedor', 'Proveedor', RelationMap::MANY_TO_ONE, array('proveedor' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // VehicxordenTableMap
