generator:
  class: sfPropelGenerator
  param:
    model_class:           cliente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              cliente
    plural:                clientes
    route_prefix:          cliente
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: Nuevo}
      fields:  ~
      list:
        title: Cliente Admin
        display: [id, nombre, rut, direccion, telefono, es_empresa]
        batch_actions: {}
        object_actions:
          _edit: {label: Editar}
          _delete: {label: Borrar}
      filter:
        class: false
      form:    ~
      edit:
        title: Editar Cliente "%%nombre%%"
        actions:
          _save: { label: Guardar }
          _list: { label: Volver }
      new:
        title: Nuevo Cliente
        actions:
          _save: {label: Guardar}
          _list: {label: Volver}
