generator:
  class: sfPropelGenerator
  param:
    model_class:           vehiculo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              vehiculo
    plural:                vehiculos
    route_prefix:          vehiculo
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: Nuevo}
      fields:  ~
      list:
        title: Vehículo Admin
        batch_actions: {}
        object_actions:
          _edit: {label: Editar}
          _delete: {label: Borrar}
      filter:
        class: false
      form:    ~
      edit:
        title: Editar Vehículo "%%descripcion%%"
        actions:
          _save: { label: Guardar }
          _list: { label: Volver }
      new:
        title: Nuevo Vehículo
        actions:
          _save: {label: Guardar}
          _list: {label: Volver}
