<?php

/**
 * Base class that represents a row from the 'vehiculo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 07/28/10 15:21:17
 *
 * @package    lib.model.om
 */
abstract class BaseVehiculo extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        VehiculoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the marca field.
	 * @var        string
	 */
	protected $marca;

	/**
	 * The value for the modelo field.
	 * @var        string
	 */
	protected $modelo;

	/**
	 * The value for the ano field.
	 * @var        int
	 */
	protected $ano;

	/**
	 * The value for the matricula field.
	 * @var        string
	 */
	protected $matricula;

	/**
	 * The value for the capacidad field.
	 * @var        int
	 */
	protected $capacidad;

	/**
	 * The value for the proveedor field.
	 * @var        int
	 */
	protected $proveedor;

	/**
	 * @var        Proveedor
	 */
	protected $aProveedorRelatedByProveedor;

	/**
	 * @var        array Vehicxorden[] Collection to store aggregation of Vehicxorden objects.
	 */
	protected $collVehicxordens;

	/**
	 * @var        Criteria The criteria used to select the current contents of collVehicxordens.
	 */
	private $lastVehicxordenCriteria = null;

	/**
	 * @var        array Pasajero[] Collection to store aggregation of Pasajero objects.
	 */
	protected $collPasajeros;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPasajeros.
	 */
	private $lastPasajeroCriteria = null;

	/**
	 * @var        array Gasto[] Collection to store aggregation of Gasto objects.
	 */
	protected $collGastos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collGastos.
	 */
	private $lastGastoCriteria = null;

	/**
	 * @var        array Remito[] Collection to store aggregation of Remito objects.
	 */
	protected $collRemitos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRemitos.
	 */
	private $lastRemitoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'VehiculoPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [marca] column value.
	 * 
	 * @return     string
	 */
	public function getMarca()
	{
		return $this->marca;
	}

	/**
	 * Get the [modelo] column value.
	 * 
	 * @return     string
	 */
	public function getModelo()
	{
		return $this->modelo;
	}

	/**
	 * Get the [ano] column value.
	 * 
	 * @return     int
	 */
	public function getAno()
	{
		return $this->ano;
	}

	/**
	 * Get the [matricula] column value.
	 * 
	 * @return     string
	 */
	public function getMatricula()
	{
		return $this->matricula;
	}

	/**
	 * Get the [capacidad] column value.
	 * 
	 * @return     int
	 */
	public function getCapacidad()
	{
		return $this->capacidad;
	}

	/**
	 * Get the [proveedor] column value.
	 * 
	 * @return     int
	 */
	public function getProveedor()
	{
		return $this->proveedor;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = VehiculoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = VehiculoPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [marca] column.
	 * 
	 * @param      string $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setMarca($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->marca !== $v) {
			$this->marca = $v;
			$this->modifiedColumns[] = VehiculoPeer::MARCA;
		}

		return $this;
	} // setMarca()

	/**
	 * Set the value of [modelo] column.
	 * 
	 * @param      string $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setModelo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->modelo !== $v) {
			$this->modelo = $v;
			$this->modifiedColumns[] = VehiculoPeer::MODELO;
		}

		return $this;
	} // setModelo()

	/**
	 * Set the value of [ano] column.
	 * 
	 * @param      int $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setAno($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->ano !== $v) {
			$this->ano = $v;
			$this->modifiedColumns[] = VehiculoPeer::ANO;
		}

		return $this;
	} // setAno()

	/**
	 * Set the value of [matricula] column.
	 * 
	 * @param      string $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setMatricula($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->matricula !== $v) {
			$this->matricula = $v;
			$this->modifiedColumns[] = VehiculoPeer::MATRICULA;
		}

		return $this;
	} // setMatricula()

	/**
	 * Set the value of [capacidad] column.
	 * 
	 * @param      int $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setCapacidad($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->capacidad !== $v) {
			$this->capacidad = $v;
			$this->modifiedColumns[] = VehiculoPeer::CAPACIDAD;
		}

		return $this;
	} // setCapacidad()

	/**
	 * Set the value of [proveedor] column.
	 * 
	 * @param      int $v new value
	 * @return     Vehiculo The current object (for fluent API support)
	 */
	public function setProveedor($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->proveedor !== $v) {
			$this->proveedor = $v;
			$this->modifiedColumns[] = VehiculoPeer::PROVEEDOR;
		}

		if ($this->aProveedorRelatedByProveedor !== null && $this->aProveedorRelatedByProveedor->getId() !== $v) {
			$this->aProveedorRelatedByProveedor = null;
		}

		return $this;
	} // setProveedor()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->descripcion = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->marca = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->modelo = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->ano = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->matricula = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->capacidad = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->proveedor = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = VehiculoPeer::NUM_COLUMNS - VehiculoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Vehiculo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aProveedorRelatedByProveedor !== null && $this->proveedor !== $this->aProveedorRelatedByProveedor->getId()) {
			$this->aProveedorRelatedByProveedor = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VehiculoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = VehiculoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aProveedorRelatedByProveedor = null;
			$this->collVehicxordens = null;
			$this->lastVehicxordenCriteria = null;

			$this->collPasajeros = null;
			$this->lastPasajeroCriteria = null;

			$this->collGastos = null;
			$this->lastGastoCriteria = null;

			$this->collRemitos = null;
			$this->lastRemitoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VehiculoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseVehiculo:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				VehiculoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseVehiculo:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VehiculoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseVehiculo:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseVehiculo:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				VehiculoPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProveedorRelatedByProveedor !== null) {
				if ($this->aProveedorRelatedByProveedor->isModified() || $this->aProveedorRelatedByProveedor->isNew()) {
					$affectedRows += $this->aProveedorRelatedByProveedor->save($con);
				}
				$this->setProveedorRelatedByProveedor($this->aProveedorRelatedByProveedor);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = VehiculoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = VehiculoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += VehiculoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collVehicxordens !== null) {
				foreach ($this->collVehicxordens as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPasajeros !== null) {
				foreach ($this->collPasajeros as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collGastos !== null) {
				foreach ($this->collGastos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRemitos !== null) {
				foreach ($this->collRemitos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aProveedorRelatedByProveedor !== null) {
				if (!$this->aProveedorRelatedByProveedor->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aProveedorRelatedByProveedor->getValidationFailures());
				}
			}


			if (($retval = VehiculoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collVehicxordens !== null) {
					foreach ($this->collVehicxordens as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPasajeros !== null) {
					foreach ($this->collPasajeros as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collGastos !== null) {
					foreach ($this->collGastos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRemitos !== null) {
					foreach ($this->collRemitos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VehiculoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getDescripcion();
				break;
			case 2:
				return $this->getMarca();
				break;
			case 3:
				return $this->getModelo();
				break;
			case 4:
				return $this->getAno();
				break;
			case 5:
				return $this->getMatricula();
				break;
			case 6:
				return $this->getCapacidad();
				break;
			case 7:
				return $this->getProveedor();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = VehiculoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getDescripcion(),
			$keys[2] => $this->getMarca(),
			$keys[3] => $this->getModelo(),
			$keys[4] => $this->getAno(),
			$keys[5] => $this->getMatricula(),
			$keys[6] => $this->getCapacidad(),
			$keys[7] => $this->getProveedor(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VehiculoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setDescripcion($value);
				break;
			case 2:
				$this->setMarca($value);
				break;
			case 3:
				$this->setModelo($value);
				break;
			case 4:
				$this->setAno($value);
				break;
			case 5:
				$this->setMatricula($value);
				break;
			case 6:
				$this->setCapacidad($value);
				break;
			case 7:
				$this->setProveedor($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = VehiculoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDescripcion($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setMarca($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setModelo($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAno($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMatricula($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCapacidad($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setProveedor($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);

		if ($this->isColumnModified(VehiculoPeer::ID)) $criteria->add(VehiculoPeer::ID, $this->id);
		if ($this->isColumnModified(VehiculoPeer::DESCRIPCION)) $criteria->add(VehiculoPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(VehiculoPeer::MARCA)) $criteria->add(VehiculoPeer::MARCA, $this->marca);
		if ($this->isColumnModified(VehiculoPeer::MODELO)) $criteria->add(VehiculoPeer::MODELO, $this->modelo);
		if ($this->isColumnModified(VehiculoPeer::ANO)) $criteria->add(VehiculoPeer::ANO, $this->ano);
		if ($this->isColumnModified(VehiculoPeer::MATRICULA)) $criteria->add(VehiculoPeer::MATRICULA, $this->matricula);
		if ($this->isColumnModified(VehiculoPeer::CAPACIDAD)) $criteria->add(VehiculoPeer::CAPACIDAD, $this->capacidad);
		if ($this->isColumnModified(VehiculoPeer::PROVEEDOR)) $criteria->add(VehiculoPeer::PROVEEDOR, $this->proveedor);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);

		$criteria->add(VehiculoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Vehiculo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setMarca($this->marca);

		$copyObj->setModelo($this->modelo);

		$copyObj->setAno($this->ano);

		$copyObj->setMatricula($this->matricula);

		$copyObj->setCapacidad($this->capacidad);

		$copyObj->setProveedor($this->proveedor);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getVehicxordens() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addVehicxorden($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPasajeros() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPasajero($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getGastos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addGasto($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRemitos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRemito($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Vehiculo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     VehiculoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new VehiculoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Proveedor object.
	 *
	 * @param      Proveedor $v
	 * @return     Vehiculo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setProveedorRelatedByProveedor(Proveedor $v = null)
	{
		if ($v === null) {
			$this->setProveedor(NULL);
		} else {
			$this->setProveedor($v->getId());
		}

		$this->aProveedorRelatedByProveedor = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Proveedor object, it will not be re-added.
		if ($v !== null) {
			$v->addVehiculo($this);
		}

		return $this;
	}


	/**
	 * Get the associated Proveedor object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Proveedor The associated Proveedor object.
	 * @throws     PropelException
	 */
	public function getProveedorRelatedByProveedor(PropelPDO $con = null)
	{
		if ($this->aProveedorRelatedByProveedor === null && ($this->proveedor !== null)) {
			$this->aProveedorRelatedByProveedor = ProveedorPeer::retrieveByPk($this->proveedor);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aProveedorRelatedByProveedor->addVehiculos($this);
			 */
		}
		return $this->aProveedorRelatedByProveedor;
	}

	/**
	 * Clears out the collVehicxordens collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addVehicxordens()
	 */
	public function clearVehicxordens()
	{
		$this->collVehicxordens = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collVehicxordens collection (array).
	 *
	 * By default this just sets the collVehicxordens collection to an empty array (like clearcollVehicxordens());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initVehicxordens()
	{
		$this->collVehicxordens = array();
	}

	/**
	 * Gets an array of Vehicxorden objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Vehiculo has previously been saved, it will retrieve
	 * related Vehicxordens from storage. If this Vehiculo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Vehicxorden[]
	 * @throws     PropelException
	 */
	public function getVehicxordens($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVehicxordens === null) {
			if ($this->isNew()) {
			   $this->collVehicxordens = array();
			} else {

				$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

				VehicxordenPeer::addSelectColumns($criteria);
				$this->collVehicxordens = VehicxordenPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

				VehicxordenPeer::addSelectColumns($criteria);
				if (!isset($this->lastVehicxordenCriteria) || !$this->lastVehicxordenCriteria->equals($criteria)) {
					$this->collVehicxordens = VehicxordenPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastVehicxordenCriteria = $criteria;
		return $this->collVehicxordens;
	}

	/**
	 * Returns the number of related Vehicxorden objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Vehicxorden objects.
	 * @throws     PropelException
	 */
	public function countVehicxordens(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collVehicxordens === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

				$count = VehicxordenPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

				if (!isset($this->lastVehicxordenCriteria) || !$this->lastVehicxordenCriteria->equals($criteria)) {
					$count = VehicxordenPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collVehicxordens);
				}
			} else {
				$count = count($this->collVehicxordens);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Vehicxorden object to this object
	 * through the Vehicxorden foreign key attribute.
	 *
	 * @param      Vehicxorden $l Vehicxorden
	 * @return     void
	 * @throws     PropelException
	 */
	public function addVehicxorden(Vehicxorden $l)
	{
		if ($this->collVehicxordens === null) {
			$this->initVehicxordens();
		}
		if (!in_array($l, $this->collVehicxordens, true)) { // only add it if the **same** object is not already associated
			array_push($this->collVehicxordens, $l);
			$l->setVehiculo($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Vehicxordens from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getVehicxordensJoinChoferRelatedByChofer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVehicxordens === null) {
			if ($this->isNew()) {
				$this->collVehicxordens = array();
			} else {

				$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

				$this->collVehicxordens = VehicxordenPeer::doSelectJoinChoferRelatedByChofer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

			if (!isset($this->lastVehicxordenCriteria) || !$this->lastVehicxordenCriteria->equals($criteria)) {
				$this->collVehicxordens = VehicxordenPeer::doSelectJoinChoferRelatedByChofer($criteria, $con, $join_behavior);
			}
		}
		$this->lastVehicxordenCriteria = $criteria;

		return $this->collVehicxordens;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Vehicxordens from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getVehicxordensJoinProveedorRelatedByProveedor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collVehicxordens === null) {
			if ($this->isNew()) {
				$this->collVehicxordens = array();
			} else {

				$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

				$this->collVehicxordens = VehicxordenPeer::doSelectJoinProveedorRelatedByProveedor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(VehicxordenPeer::IDVEHICULO, $this->id);

			if (!isset($this->lastVehicxordenCriteria) || !$this->lastVehicxordenCriteria->equals($criteria)) {
				$this->collVehicxordens = VehicxordenPeer::doSelectJoinProveedorRelatedByProveedor($criteria, $con, $join_behavior);
			}
		}
		$this->lastVehicxordenCriteria = $criteria;

		return $this->collVehicxordens;
	}

	/**
	 * Clears out the collPasajeros collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPasajeros()
	 */
	public function clearPasajeros()
	{
		$this->collPasajeros = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPasajeros collection (array).
	 *
	 * By default this just sets the collPasajeros collection to an empty array (like clearcollPasajeros());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPasajeros()
	{
		$this->collPasajeros = array();
	}

	/**
	 * Gets an array of Pasajero objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Vehiculo has previously been saved, it will retrieve
	 * related Pasajeros from storage. If this Vehiculo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Pasajero[]
	 * @throws     PropelException
	 */
	public function getPasajeros($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPasajeros === null) {
			if ($this->isNew()) {
			   $this->collPasajeros = array();
			} else {

				$criteria->add(PasajeroPeer::VEHICULO, $this->id);

				PasajeroPeer::addSelectColumns($criteria);
				$this->collPasajeros = PasajeroPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PasajeroPeer::VEHICULO, $this->id);

				PasajeroPeer::addSelectColumns($criteria);
				if (!isset($this->lastPasajeroCriteria) || !$this->lastPasajeroCriteria->equals($criteria)) {
					$this->collPasajeros = PasajeroPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPasajeroCriteria = $criteria;
		return $this->collPasajeros;
	}

	/**
	 * Returns the number of related Pasajero objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Pasajero objects.
	 * @throws     PropelException
	 */
	public function countPasajeros(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPasajeros === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PasajeroPeer::VEHICULO, $this->id);

				$count = PasajeroPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PasajeroPeer::VEHICULO, $this->id);

				if (!isset($this->lastPasajeroCriteria) || !$this->lastPasajeroCriteria->equals($criteria)) {
					$count = PasajeroPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPasajeros);
				}
			} else {
				$count = count($this->collPasajeros);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Pasajero object to this object
	 * through the Pasajero foreign key attribute.
	 *
	 * @param      Pasajero $l Pasajero
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPasajero(Pasajero $l)
	{
		if ($this->collPasajeros === null) {
			$this->initPasajeros();
		}
		if (!in_array($l, $this->collPasajeros, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPasajeros, $l);
			$l->setVehiculoRelatedByVehiculo($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Pasajeros from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getPasajerosJoinZona($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPasajeros === null) {
			if ($this->isNew()) {
				$this->collPasajeros = array();
			} else {

				$criteria->add(PasajeroPeer::VEHICULO, $this->id);

				$this->collPasajeros = PasajeroPeer::doSelectJoinZona($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PasajeroPeer::VEHICULO, $this->id);

			if (!isset($this->lastPasajeroCriteria) || !$this->lastPasajeroCriteria->equals($criteria)) {
				$this->collPasajeros = PasajeroPeer::doSelectJoinZona($criteria, $con, $join_behavior);
			}
		}
		$this->lastPasajeroCriteria = $criteria;

		return $this->collPasajeros;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Pasajeros from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getPasajerosJoinOrdenRelatedByOrden($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPasajeros === null) {
			if ($this->isNew()) {
				$this->collPasajeros = array();
			} else {

				$criteria->add(PasajeroPeer::VEHICULO, $this->id);

				$this->collPasajeros = PasajeroPeer::doSelectJoinOrdenRelatedByOrden($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PasajeroPeer::VEHICULO, $this->id);

			if (!isset($this->lastPasajeroCriteria) || !$this->lastPasajeroCriteria->equals($criteria)) {
				$this->collPasajeros = PasajeroPeer::doSelectJoinOrdenRelatedByOrden($criteria, $con, $join_behavior);
			}
		}
		$this->lastPasajeroCriteria = $criteria;

		return $this->collPasajeros;
	}

	/**
	 * Clears out the collGastos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addGastos()
	 */
	public function clearGastos()
	{
		$this->collGastos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collGastos collection (array).
	 *
	 * By default this just sets the collGastos collection to an empty array (like clearcollGastos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initGastos()
	{
		$this->collGastos = array();
	}

	/**
	 * Gets an array of Gasto objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Vehiculo has previously been saved, it will retrieve
	 * related Gastos from storage. If this Vehiculo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Gasto[]
	 * @throws     PropelException
	 */
	public function getGastos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collGastos === null) {
			if ($this->isNew()) {
			   $this->collGastos = array();
			} else {

				$criteria->add(GastoPeer::VEHICULO, $this->id);

				GastoPeer::addSelectColumns($criteria);
				$this->collGastos = GastoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(GastoPeer::VEHICULO, $this->id);

				GastoPeer::addSelectColumns($criteria);
				if (!isset($this->lastGastoCriteria) || !$this->lastGastoCriteria->equals($criteria)) {
					$this->collGastos = GastoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastGastoCriteria = $criteria;
		return $this->collGastos;
	}

	/**
	 * Returns the number of related Gasto objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Gasto objects.
	 * @throws     PropelException
	 */
	public function countGastos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collGastos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(GastoPeer::VEHICULO, $this->id);

				$count = GastoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(GastoPeer::VEHICULO, $this->id);

				if (!isset($this->lastGastoCriteria) || !$this->lastGastoCriteria->equals($criteria)) {
					$count = GastoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collGastos);
				}
			} else {
				$count = count($this->collGastos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Gasto object to this object
	 * through the Gasto foreign key attribute.
	 *
	 * @param      Gasto $l Gasto
	 * @return     void
	 * @throws     PropelException
	 */
	public function addGasto(Gasto $l)
	{
		if ($this->collGastos === null) {
			$this->initGastos();
		}
		if (!in_array($l, $this->collGastos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collGastos, $l);
			$l->setVehiculoRelatedByVehiculo($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Gastos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getGastosJoinTipogastoRelatedByTipogasto($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collGastos === null) {
			if ($this->isNew()) {
				$this->collGastos = array();
			} else {

				$criteria->add(GastoPeer::VEHICULO, $this->id);

				$this->collGastos = GastoPeer::doSelectJoinTipogastoRelatedByTipogasto($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(GastoPeer::VEHICULO, $this->id);

			if (!isset($this->lastGastoCriteria) || !$this->lastGastoCriteria->equals($criteria)) {
				$this->collGastos = GastoPeer::doSelectJoinTipogastoRelatedByTipogasto($criteria, $con, $join_behavior);
			}
		}
		$this->lastGastoCriteria = $criteria;

		return $this->collGastos;
	}

	/**
	 * Clears out the collRemitos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRemitos()
	 */
	public function clearRemitos()
	{
		$this->collRemitos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRemitos collection (array).
	 *
	 * By default this just sets the collRemitos collection to an empty array (like clearcollRemitos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRemitos()
	{
		$this->collRemitos = array();
	}

	/**
	 * Gets an array of Remito objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Vehiculo has previously been saved, it will retrieve
	 * related Remitos from storage. If this Vehiculo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Remito[]
	 * @throws     PropelException
	 */
	public function getRemitos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
			   $this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

				RemitoPeer::addSelectColumns($criteria);
				$this->collRemitos = RemitoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

				RemitoPeer::addSelectColumns($criteria);
				if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
					$this->collRemitos = RemitoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRemitoCriteria = $criteria;
		return $this->collRemitos;
	}

	/**
	 * Returns the number of related Remito objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Remito objects.
	 * @throws     PropelException
	 */
	public function countRemitos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

				$count = RemitoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

				if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
					$count = RemitoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collRemitos);
				}
			} else {
				$count = count($this->collRemitos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Remito object to this object
	 * through the Remito foreign key attribute.
	 *
	 * @param      Remito $l Remito
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRemito(Remito $l)
	{
		if ($this->collRemitos === null) {
			$this->initRemitos();
		}
		if (!in_array($l, $this->collRemitos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRemitos, $l);
			$l->setVehiculo($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Remitos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getRemitosJoinOrden($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

				$this->collRemitos = RemitoPeer::doSelectJoinOrden($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

			if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
				$this->collRemitos = RemitoPeer::doSelectJoinOrden($criteria, $con, $join_behavior);
			}
		}
		$this->lastRemitoCriteria = $criteria;

		return $this->collRemitos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Remitos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getRemitosJoinMonedaRelatedByMoneda($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

				$this->collRemitos = RemitoPeer::doSelectJoinMonedaRelatedByMoneda($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

			if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
				$this->collRemitos = RemitoPeer::doSelectJoinMonedaRelatedByMoneda($criteria, $con, $join_behavior);
			}
		}
		$this->lastRemitoCriteria = $criteria;

		return $this->collRemitos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Vehiculo is new, it will return
	 * an empty collection; or if this Vehiculo has previously
	 * been saved, it will retrieve related Remitos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Vehiculo.
	 */
	public function getRemitosJoinProveedorRelatedByProveedor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(VehiculoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

				$this->collRemitos = RemitoPeer::doSelectJoinProveedorRelatedByProveedor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RemitoPeer::IDVEHICULO, $this->id);

			if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
				$this->collRemitos = RemitoPeer::doSelectJoinProveedorRelatedByProveedor($criteria, $con, $join_behavior);
			}
		}
		$this->lastRemitoCriteria = $criteria;

		return $this->collRemitos;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collVehicxordens) {
				foreach ((array) $this->collVehicxordens as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPasajeros) {
				foreach ((array) $this->collPasajeros as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collGastos) {
				foreach ((array) $this->collGastos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRemitos) {
				foreach ((array) $this->collRemitos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collVehicxordens = null;
		$this->collPasajeros = null;
		$this->collGastos = null;
		$this->collRemitos = null;
			$this->aProveedorRelatedByProveedor = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseVehiculo:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseVehiculo::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseVehiculo
