<?php

/**
 * Base class that represents a row from the 'factura' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 07/28/10 15:21:18
 *
 * @package    lib.model.om
 */
abstract class BaseFactura extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FacturaPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the num_fac field.
	 * @var        int
	 */
	protected $num_fac;

	/**
	 * The value for the cliente field.
	 * @var        int
	 */
	protected $cliente;

	/**
	 * The value for the fecha_fact field.
	 * @var        string
	 */
	protected $fecha_fact;

	/**
	 * The value for the desc_generica field.
	 * @var        string
	 */
	protected $desc_generica;

	/**
	 * The value for the iva field.
	 * @var        int
	 */
	protected $iva;

	/**
	 * The value for the subtotal field.
	 * @var        string
	 */
	protected $subtotal;

	/**
	 * The value for the total field.
	 * @var        string
	 */
	protected $total;

	/**
	 * The value for the moneda field.
	 * @var        int
	 */
	protected $moneda;

	/**
	 * The value for the formapago field.
	 * @var        string
	 */
	protected $formapago;

	/**
	 * The value for the fechapago field.
	 * @var        string
	 */
	protected $fechapago;

	/**
	 * @var        Cliente
	 */
	protected $aClienteRelatedByCliente;

	/**
	 * @var        Moneda
	 */
	protected $aMonedaRelatedByMoneda;

	/**
	 * @var        array Lineafact[] Collection to store aggregation of Lineafact objects.
	 */
	protected $collLineafacts;

	/**
	 * @var        Criteria The criteria used to select the current contents of collLineafacts.
	 */
	private $lastLineafactCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FacturaPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [num_fac] column value.
	 * 
	 * @return     int
	 */
	public function getNumFac()
	{
		return $this->num_fac;
	}

	/**
	 * Get the [cliente] column value.
	 * 
	 * @return     int
	 */
	public function getCliente()
	{
		return $this->cliente;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_fact] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaFact($format = 'Y-m-d')
	{
		if ($this->fecha_fact === null) {
			return null;
		}


		if ($this->fecha_fact === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_fact);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_fact, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [desc_generica] column value.
	 * 
	 * @return     string
	 */
	public function getDescGenerica()
	{
		return $this->desc_generica;
	}

	/**
	 * Get the [iva] column value.
	 * 
	 * @return     int
	 */
	public function getIva()
	{
		return $this->iva;
	}

	/**
	 * Get the [subtotal] column value.
	 * 
	 * @return     string
	 */
	public function getSubtotal()
	{
		return $this->subtotal;
	}

	/**
	 * Get the [total] column value.
	 * 
	 * @return     string
	 */
	public function getTotal()
	{
		return $this->total;
	}

	/**
	 * Get the [moneda] column value.
	 * 
	 * @return     int
	 */
	public function getMoneda()
	{
		return $this->moneda;
	}

	/**
	 * Get the [formapago] column value.
	 * 
	 * @return     string
	 */
	public function getFormapago()
	{
		return $this->formapago;
	}

	/**
	 * Get the [optionally formatted] temporal [fechapago] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechapago($format = 'Y-m-d')
	{
		if ($this->fechapago === null) {
			return null;
		}


		if ($this->fechapago === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechapago);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechapago, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = FacturaPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [num_fac] column.
	 * 
	 * @param      int $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setNumFac($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->num_fac !== $v) {
			$this->num_fac = $v;
			$this->modifiedColumns[] = FacturaPeer::NUM_FAC;
		}

		return $this;
	} // setNumFac()

	/**
	 * Set the value of [cliente] column.
	 * 
	 * @param      int $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setCliente($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cliente !== $v) {
			$this->cliente = $v;
			$this->modifiedColumns[] = FacturaPeer::CLIENTE;
		}

		if ($this->aClienteRelatedByCliente !== null && $this->aClienteRelatedByCliente->getId() !== $v) {
			$this->aClienteRelatedByCliente = null;
		}

		return $this;
	} // setCliente()

	/**
	 * Sets the value of [fecha_fact] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setFechaFact($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_fact !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_fact !== null && $tmpDt = new DateTime($this->fecha_fact)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_fact = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = FacturaPeer::FECHA_FACT;
			}
		} // if either are not null

		return $this;
	} // setFechaFact()

	/**
	 * Set the value of [desc_generica] column.
	 * 
	 * @param      string $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setDescGenerica($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->desc_generica !== $v) {
			$this->desc_generica = $v;
			$this->modifiedColumns[] = FacturaPeer::DESC_GENERICA;
		}

		return $this;
	} // setDescGenerica()

	/**
	 * Set the value of [iva] column.
	 * 
	 * @param      int $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setIva($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->iva !== $v) {
			$this->iva = $v;
			$this->modifiedColumns[] = FacturaPeer::IVA;
		}

		return $this;
	} // setIva()

	/**
	 * Set the value of [subtotal] column.
	 * 
	 * @param      string $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setSubtotal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->subtotal !== $v) {
			$this->subtotal = $v;
			$this->modifiedColumns[] = FacturaPeer::SUBTOTAL;
		}

		return $this;
	} // setSubtotal()

	/**
	 * Set the value of [total] column.
	 * 
	 * @param      string $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setTotal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->total !== $v) {
			$this->total = $v;
			$this->modifiedColumns[] = FacturaPeer::TOTAL;
		}

		return $this;
	} // setTotal()

	/**
	 * Set the value of [moneda] column.
	 * 
	 * @param      int $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setMoneda($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->moneda !== $v) {
			$this->moneda = $v;
			$this->modifiedColumns[] = FacturaPeer::MONEDA;
		}

		if ($this->aMonedaRelatedByMoneda !== null && $this->aMonedaRelatedByMoneda->getId() !== $v) {
			$this->aMonedaRelatedByMoneda = null;
		}

		return $this;
	} // setMoneda()

	/**
	 * Set the value of [formapago] column.
	 * 
	 * @param      string $v new value
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setFormapago($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->formapago !== $v) {
			$this->formapago = $v;
			$this->modifiedColumns[] = FacturaPeer::FORMAPAGO;
		}

		return $this;
	} // setFormapago()

	/**
	 * Sets the value of [fechapago] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Factura The current object (for fluent API support)
	 */
	public function setFechapago($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechapago !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechapago !== null && $tmpDt = new DateTime($this->fechapago)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechapago = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = FacturaPeer::FECHAPAGO;
			}
		} // if either are not null

		return $this;
	} // setFechapago()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->num_fac = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->cliente = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->fecha_fact = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->desc_generica = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->iva = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->subtotal = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->total = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->moneda = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->formapago = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->fechapago = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Factura object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aClienteRelatedByCliente !== null && $this->cliente !== $this->aClienteRelatedByCliente->getId()) {
			$this->aClienteRelatedByCliente = null;
		}
		if ($this->aMonedaRelatedByMoneda !== null && $this->moneda !== $this->aMonedaRelatedByMoneda->getId()) {
			$this->aMonedaRelatedByMoneda = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FacturaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aClienteRelatedByCliente = null;
			$this->aMonedaRelatedByMoneda = null;
			$this->collLineafacts = null;
			$this->lastLineafactCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFactura:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FacturaPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFactura:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFactura:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFactura:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FacturaPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aClienteRelatedByCliente !== null) {
				if ($this->aClienteRelatedByCliente->isModified() || $this->aClienteRelatedByCliente->isNew()) {
					$affectedRows += $this->aClienteRelatedByCliente->save($con);
				}
				$this->setClienteRelatedByCliente($this->aClienteRelatedByCliente);
			}

			if ($this->aMonedaRelatedByMoneda !== null) {
				if ($this->aMonedaRelatedByMoneda->isModified() || $this->aMonedaRelatedByMoneda->isNew()) {
					$affectedRows += $this->aMonedaRelatedByMoneda->save($con);
				}
				$this->setMonedaRelatedByMoneda($this->aMonedaRelatedByMoneda);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FacturaPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FacturaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FacturaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collLineafacts !== null) {
				foreach ($this->collLineafacts as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aClienteRelatedByCliente !== null) {
				if (!$this->aClienteRelatedByCliente->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aClienteRelatedByCliente->getValidationFailures());
				}
			}

			if ($this->aMonedaRelatedByMoneda !== null) {
				if (!$this->aMonedaRelatedByMoneda->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMonedaRelatedByMoneda->getValidationFailures());
				}
			}


			if (($retval = FacturaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collLineafacts !== null) {
					foreach ($this->collLineafacts as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FacturaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNumFac();
				break;
			case 2:
				return $this->getCliente();
				break;
			case 3:
				return $this->getFechaFact();
				break;
			case 4:
				return $this->getDescGenerica();
				break;
			case 5:
				return $this->getIva();
				break;
			case 6:
				return $this->getSubtotal();
				break;
			case 7:
				return $this->getTotal();
				break;
			case 8:
				return $this->getMoneda();
				break;
			case 9:
				return $this->getFormapago();
				break;
			case 10:
				return $this->getFechapago();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FacturaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNumFac(),
			$keys[2] => $this->getCliente(),
			$keys[3] => $this->getFechaFact(),
			$keys[4] => $this->getDescGenerica(),
			$keys[5] => $this->getIva(),
			$keys[6] => $this->getSubtotal(),
			$keys[7] => $this->getTotal(),
			$keys[8] => $this->getMoneda(),
			$keys[9] => $this->getFormapago(),
			$keys[10] => $this->getFechapago(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FacturaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNumFac($value);
				break;
			case 2:
				$this->setCliente($value);
				break;
			case 3:
				$this->setFechaFact($value);
				break;
			case 4:
				$this->setDescGenerica($value);
				break;
			case 5:
				$this->setIva($value);
				break;
			case 6:
				$this->setSubtotal($value);
				break;
			case 7:
				$this->setTotal($value);
				break;
			case 8:
				$this->setMoneda($value);
				break;
			case 9:
				$this->setFormapago($value);
				break;
			case 10:
				$this->setFechapago($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FacturaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNumFac($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCliente($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFechaFact($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDescGenerica($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setIva($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setSubtotal($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setTotal($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setMoneda($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFormapago($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setFechapago($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FacturaPeer::DATABASE_NAME);

		if ($this->isColumnModified(FacturaPeer::ID)) $criteria->add(FacturaPeer::ID, $this->id);
		if ($this->isColumnModified(FacturaPeer::NUM_FAC)) $criteria->add(FacturaPeer::NUM_FAC, $this->num_fac);
		if ($this->isColumnModified(FacturaPeer::CLIENTE)) $criteria->add(FacturaPeer::CLIENTE, $this->cliente);
		if ($this->isColumnModified(FacturaPeer::FECHA_FACT)) $criteria->add(FacturaPeer::FECHA_FACT, $this->fecha_fact);
		if ($this->isColumnModified(FacturaPeer::DESC_GENERICA)) $criteria->add(FacturaPeer::DESC_GENERICA, $this->desc_generica);
		if ($this->isColumnModified(FacturaPeer::IVA)) $criteria->add(FacturaPeer::IVA, $this->iva);
		if ($this->isColumnModified(FacturaPeer::SUBTOTAL)) $criteria->add(FacturaPeer::SUBTOTAL, $this->subtotal);
		if ($this->isColumnModified(FacturaPeer::TOTAL)) $criteria->add(FacturaPeer::TOTAL, $this->total);
		if ($this->isColumnModified(FacturaPeer::MONEDA)) $criteria->add(FacturaPeer::MONEDA, $this->moneda);
		if ($this->isColumnModified(FacturaPeer::FORMAPAGO)) $criteria->add(FacturaPeer::FORMAPAGO, $this->formapago);
		if ($this->isColumnModified(FacturaPeer::FECHAPAGO)) $criteria->add(FacturaPeer::FECHAPAGO, $this->fechapago);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FacturaPeer::DATABASE_NAME);

		$criteria->add(FacturaPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Factura (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNumFac($this->num_fac);

		$copyObj->setCliente($this->cliente);

		$copyObj->setFechaFact($this->fecha_fact);

		$copyObj->setDescGenerica($this->desc_generica);

		$copyObj->setIva($this->iva);

		$copyObj->setSubtotal($this->subtotal);

		$copyObj->setTotal($this->total);

		$copyObj->setMoneda($this->moneda);

		$copyObj->setFormapago($this->formapago);

		$copyObj->setFechapago($this->fechapago);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getLineafacts() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addLineafact($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Factura Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FacturaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FacturaPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Cliente object.
	 *
	 * @param      Cliente $v
	 * @return     Factura The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setClienteRelatedByCliente(Cliente $v = null)
	{
		if ($v === null) {
			$this->setCliente(NULL);
		} else {
			$this->setCliente($v->getId());
		}

		$this->aClienteRelatedByCliente = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Cliente object, it will not be re-added.
		if ($v !== null) {
			$v->addFactura($this);
		}

		return $this;
	}


	/**
	 * Get the associated Cliente object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Cliente The associated Cliente object.
	 * @throws     PropelException
	 */
	public function getClienteRelatedByCliente(PropelPDO $con = null)
	{
		if ($this->aClienteRelatedByCliente === null && ($this->cliente !== null)) {
			$this->aClienteRelatedByCliente = ClientePeer::retrieveByPk($this->cliente);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aClienteRelatedByCliente->addFacturas($this);
			 */
		}
		return $this->aClienteRelatedByCliente;
	}

	/**
	 * Declares an association between this object and a Moneda object.
	 *
	 * @param      Moneda $v
	 * @return     Factura The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMonedaRelatedByMoneda(Moneda $v = null)
	{
		if ($v === null) {
			$this->setMoneda(NULL);
		} else {
			$this->setMoneda($v->getId());
		}

		$this->aMonedaRelatedByMoneda = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Moneda object, it will not be re-added.
		if ($v !== null) {
			$v->addFactura($this);
		}

		return $this;
	}


	/**
	 * Get the associated Moneda object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Moneda The associated Moneda object.
	 * @throws     PropelException
	 */
	public function getMonedaRelatedByMoneda(PropelPDO $con = null)
	{
		if ($this->aMonedaRelatedByMoneda === null && ($this->moneda !== null)) {
			$this->aMonedaRelatedByMoneda = MonedaPeer::retrieveByPk($this->moneda);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMonedaRelatedByMoneda->addFacturas($this);
			 */
		}
		return $this->aMonedaRelatedByMoneda;
	}

	/**
	 * Clears out the collLineafacts collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addLineafacts()
	 */
	public function clearLineafacts()
	{
		$this->collLineafacts = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collLineafacts collection (array).
	 *
	 * By default this just sets the collLineafacts collection to an empty array (like clearcollLineafacts());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initLineafacts()
	{
		$this->collLineafacts = array();
	}

	/**
	 * Gets an array of Lineafact objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Factura has previously been saved, it will retrieve
	 * related Lineafacts from storage. If this Factura is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Lineafact[]
	 * @throws     PropelException
	 */
	public function getLineafacts($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FacturaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLineafacts === null) {
			if ($this->isNew()) {
			   $this->collLineafacts = array();
			} else {

				$criteria->add(LineafactPeer::FACTURA_ID, $this->id);

				LineafactPeer::addSelectColumns($criteria);
				$this->collLineafacts = LineafactPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(LineafactPeer::FACTURA_ID, $this->id);

				LineafactPeer::addSelectColumns($criteria);
				if (!isset($this->lastLineafactCriteria) || !$this->lastLineafactCriteria->equals($criteria)) {
					$this->collLineafacts = LineafactPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastLineafactCriteria = $criteria;
		return $this->collLineafacts;
	}

	/**
	 * Returns the number of related Lineafact objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Lineafact objects.
	 * @throws     PropelException
	 */
	public function countLineafacts(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FacturaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collLineafacts === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(LineafactPeer::FACTURA_ID, $this->id);

				$count = LineafactPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(LineafactPeer::FACTURA_ID, $this->id);

				if (!isset($this->lastLineafactCriteria) || !$this->lastLineafactCriteria->equals($criteria)) {
					$count = LineafactPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collLineafacts);
				}
			} else {
				$count = count($this->collLineafacts);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Lineafact object to this object
	 * through the Lineafact foreign key attribute.
	 *
	 * @param      Lineafact $l Lineafact
	 * @return     void
	 * @throws     PropelException
	 */
	public function addLineafact(Lineafact $l)
	{
		if ($this->collLineafacts === null) {
			$this->initLineafacts();
		}
		if (!in_array($l, $this->collLineafacts, true)) { // only add it if the **same** object is not already associated
			array_push($this->collLineafacts, $l);
			$l->setFactura($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Factura is new, it will return
	 * an empty collection; or if this Factura has previously
	 * been saved, it will retrieve related Lineafacts from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Factura.
	 */
	public function getLineafactsJoinOrden($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FacturaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collLineafacts === null) {
			if ($this->isNew()) {
				$this->collLineafacts = array();
			} else {

				$criteria->add(LineafactPeer::FACTURA_ID, $this->id);

				$this->collLineafacts = LineafactPeer::doSelectJoinOrden($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(LineafactPeer::FACTURA_ID, $this->id);

			if (!isset($this->lastLineafactCriteria) || !$this->lastLineafactCriteria->equals($criteria)) {
				$this->collLineafacts = LineafactPeer::doSelectJoinOrden($criteria, $con, $join_behavior);
			}
		}
		$this->lastLineafactCriteria = $criteria;

		return $this->collLineafacts;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collLineafacts) {
				foreach ((array) $this->collLineafacts as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collLineafacts = null;
			$this->aClienteRelatedByCliente = null;
			$this->aMonedaRelatedByMoneda = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFactura:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFactura::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFactura
