<?php


/**
 * This class defines the structure of the 'vehiculo' table.
 *
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 07/28/10 15:21:17
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class VehiculoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.VehiculoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('vehiculo');
		$this->setPhpName('Vehiculo');
		$this->setClassname('Vehiculo');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('DESCRIPCION', 'Descripcion', 'VARCHAR', true, 100, null);
		$this->addColumn('MARCA', 'Marca', 'VARCHAR', true, 100, null);
		$this->addColumn('MODELO', 'Modelo', 'VARCHAR', true, 150, null);
		$this->addColumn('ANO', 'Ano', 'INTEGER', true, null, null);
		$this->addColumn('MATRICULA', 'Matricula', 'VARCHAR', true, 150, null);
		$this->addColumn('CAPACIDAD', 'Capacidad', 'INTEGER', false, null, null);
		$this->addForeignKey('PROVEEDOR', 'Proveedor', 'INTEGER', 'proveedor', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('ProveedorRelatedByProveedor', 'Proveedor', RelationMap::MANY_TO_ONE, array('proveedor' => 'id', ), null, null);
    $this->addRelation('Vehicxorden', 'Vehicxorden', RelationMap::ONE_TO_MANY, array('id' => 'idVehiculo', ), null, null);
    $this->addRelation('Pasajero', 'Pasajero', RelationMap::ONE_TO_MANY, array('id' => 'vehiculo', ), null, null);
    $this->addRelation('Gasto', 'Gasto', RelationMap::ONE_TO_MANY, array('id' => 'vehiculo', ), null, null);
    $this->addRelation('Remito', 'Remito', RelationMap::ONE_TO_MANY, array('id' => 'idVehiculo', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // VehiculoTableMap
