generator:
  class: sfPropelGenerator
  param:
    model_class:           proveedor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              proveedor
    plural:                proveedors
    route_prefix:          proveedor
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: Nuevo}
      fields:  ~
      list:
        title: Proveedor Admin
        display: [id, nombre, direccion, telefono, es_empresa]
        batch_actions: {}
        object_actions:
          _edit: {label: Editar}
          _delete: {label: Borrar}
      filter:
        class: false
      form: ~
      edit:
        title: Editar Proveedor "%%nombre%%"
        actions:
          _save: { label: Guardar }
          _list: { label: Volver }

      new:
        title: Nuevo Proveedor
        actions:
          _save: {label: Guardar}
          _list: {label: Volver}
