<?php


/**
 * Skeleton subclass for representing a row from the 'lineafact' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/27/10 14:49:36
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Lineafact extends BaseLineafact {

        public function getobjOrden($idorden)
	{
                //CAMBIO
                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
               $orden = OrdenPeer::retrieveByPk($idorden);
                return $orden;

        }



} // Lineafact
