<?php


/**
 * Skeleton subclass for representing a row from the 'moneda' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/24/10 21:44:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Moneda extends BaseMoneda {

 public function __toString()
  {
    return $this->getMoneda();
  }



      public function getobjMoneda($idmoneda)
	{
                //CAMBIO
                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
                $moneda = MonedaPeer::retrieveByPk($idmoneda);
                return $moneda;
	}

        public function getAll(){
            $moneda=MonedaPeer::doSelect(new Criteria());
            return $moneda;
        }

        public function getMontoMoneda($numref){

            $c = new Criteria();
            $c->add(MonedaPeer::NUMREF,$numref,Criteria::EQUAL);
            return MonedaPeer::doSelectOne($c)->getTipocambio();
        }
} // Moneda
