<?php


/**
 * Skeleton subclass for representing a row from the 'pasajero' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/09/10 10:59:25
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Pasajero extends BasePasajero {
public function __toString()
  {
    return $this->getnombre();
  }


         public function getNombreVehiculo()
	{
//                //CAMBIO
//                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
//                $vehiculo = VehiculoPeer::retrieveByPk($this->vehiculo);
//                return $vehiculo;
             $vehiculo= new Vehiculo();
             $vehiculo = $vehiculo->getobjVehiculo($this->vehiculo);
             return $vehiculo->getDescripcion();
	}


  public function getNombreZona()
	{
		//return $this->idvehiculo;
                //CAMBIO
                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
                $zona = ZonaPeer::retrieveByPk($this->zona_id);
                return $zona;

	}

         public function getNombreOrden()
	{
		//return $this->idvehiculo;
                //CAMBIO
                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
                $orden = OrdenPeer::retrieveByPk($this->orden);
                return $orden;

	}




 public function save(PropelPDO $con = null)
{
if (is_null($con))
  {
    $con = Propel::getConnection(PasajeroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
  }

  $con->beginTransaction();
  try
  {
    $ret = parent::save($con);

    $this->updateLuceneIndex();

    $con->commit();

    return $ret;
  }
  catch (Exception $e)
  {
    $con->rollBack();
    throw $e;
  }

}


public function delete(PropelPDO $con = null)
{
  $index = PasajeroPeer::getLuceneIndex();

  if ($hit = $index->find('pk:'.$this->getId()))
  {
    $index->delete($hit->id);
  }

  return parent::delete($con);
}




public function updateLuceneIndex()
{
  $index = PasajeroPeer::getLuceneIndex();


  // remove an existing entry
  if ($hit = $index->find('pk:'.$this->getId()))
  {
    $index->delete($hit->id);
  }

  // don't index expired and non-activated jobs
//  if ($this->isExpired() || !$this->getIsActivated())
//  {
//    return;
//  }

  $doc = new Zend_Search_Lucene_Document();

  // store Cliente primary key URL to identify it in the search results
  $doc->addField(Zend_Search_Lucene_Field::UnIndexed('pk', $this->getId()));

  // index Cliente fields
  $doc->addField(Zend_Search_Lucene_Field::UnStored('nombre', $this->getNombre(), 'utf-8'));
  $doc->addField(Zend_Search_Lucene_Field::UnStored('direccion', $this->getDireccion(), 'utf-8'));
  // add job to the index
  $index->addDocument($doc);
  $index->commit();

}

    public function retornarVehiculo(){
        return VehiculoPeer::retrieveByPK($this->getVehiculo());

    }
    public function retornarOrden(){
        return OrdenPeer::retrieveByPK($this->getOrden());
    }
} // Pasajero
