<?php


/**
 * Skeleton subclass for representing a row from the 'tipoGasto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/28/10 10:59:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tipogasto extends BaseTipogasto {

    public function __toString()
  {
    return $this->getDescripcion();
  }
         public function getobjTipoGasto($idTipo)
	{
                //CAMBIO
                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
                $tgasto = TipogastoPeer::retrieveByPk($idTipo);
                return $tgasto;
	}
} // Tipogasto
