<?php


/**
 * Skeleton subclass for performing query and update operations on the 'vehiculo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/11/10 21:23:51
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VehiculoPeer extends BaseVehiculoPeer {

//
//   static public function getVehicDisponible()
//      {
//    $criteria = new Criteria();
//    $criteria->addJoin(self::ID, VehicxordenPeer::IDVEHICULO);
//    $criteria->add(VehicxordenPeer::CANTPASAJEROS, self::CAPACIDAD, Criteria::LESS_THAN);
//   //$criteria->setDistinct();
//    return self::doSelect($criteria);
//  }


   


} // VehiculoPeer
