<?php


/**
 * Skeleton subclass for representing a row from the 'gasto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/28/10 13:08:03
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Gasto extends BaseGasto {
       public function getDescripVehiculo()
	{
//                //CAMBIO
//                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
//                $vehiculo = VehiculoPeer::retrieveByPk($this->vehiculo);
//                return $vehiculo;
             $objvehiculo=new Vehiculo();
             $objvehiculo= $objvehiculo->getobjVehiculo($this->getVehiculo());
             return $objvehiculo->getDescripcion();
	}
        public function getDescripGasto()
	{
//                //CAMBIO
//                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
//                $vehiculo = VehiculoPeer::retrieveByPk($this->vehiculo);
//                return $vehiculo;
             $objGasto=new Tipogasto();
             $objGasto= $objGasto->getobjTipoGasto($this->getTipogasto());
             return $objGasto->getDescripcion();
	}
} // Gasto
