<?php


/**
 * Skeleton subclass for representing a row from the 'tarifa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 06/12/10 18:44:35
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tarifa extends BaseTarifa {


    public function getPrecio($param){

        $c= new Criteria();
        $c->add(TarifaPeer::DESCRIPCION, $param ,Criteria::EQUAL);
        $tarif=TarifaPeer::doSelectOne($c);
        return $tarif->getValor();
    }
} // Tarifa
