<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tmpfactura' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 06/13/10 01:36:47
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TmpfacturaPeer extends BaseTmpfacturaPeer {

} // TmpfacturaPeer
