<?php


/**
 * Skeleton subclass for representing a row from the 'tmplineafact' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 06/13/10 01:36:48
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tmplineafact extends BaseTmplineafact {

    public function getKmTotal(){
        return $this->getOrden()->getKilometros();
    }

     public function getHoras(){
        return $this->getOrden()->getHoras();
    }

     public function getPrecioKM($mon){
        return $this->getOrden()->getPrecioKM($mon);
    }


     public function getPrecioHora($mon){
        return $this->getOrden()->getPrecioHora($mon);
    }

       

} // Tmplineafact
