<?php


/**
 * Skeleton subclass for representing a row from the 'vehiculo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/11/10 21:23:51
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Vehiculo extends BaseVehiculo {
public function __toString()
  {
    return $this->getDescripcion();
  }

           public function getobjVehiculo($idvehiculo)
	{
                //CAMBIO
                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
                $vehiculo = VehiculoPeer::retrieveByPk($idvehiculo);
                return $vehiculo;
	}

} // Vehiculo
