<?php


/**
 * Skeleton subclass for representing a row from the 'zona' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 05/09/10 10:59:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Zona extends BaseZona {

  public function __toString()
  {
    return $this->getdescripcion();
  }

    public function getNombreLocalidad()
	{
		//return $this->idvehiculo;
                //CAMBIO
                //Obtengo el vehiculo que corresponde al ID y devuelvo el nombre
                $localidad = LocalidadPeer::retrieveByPk($this->localidad_id);
                return $localidad;
	}


} // Zona
