generator:
  class: sfPropelGenerator
  param:
    model_class:           zona
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              zona
    plural:                zonas
    route_prefix:          zona
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
         _new: {label: Nuevo}
      fields:  ~
      list:
        title: Zona Admin
        batch_actions: {}
        object_actions:
          _edit: {label: Editar}
          _delete: {label: Borrar}
      filter:
        class: false
      form:    ~
      edit:
        title: Editar Zona "%%descripcion%%"
        actions:
          _save: { label: Guardar }
          _list: { label: Volver }
      new:
        title: Nueva Zona
        actions:
          _save: {label: Guardar}
          _list: {label: Volver}
