generator:
  class: sfPropelGenerator
  param:
    model_class:           localidad
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              localidad
    plural:                localidads
    route_prefix:          localidad
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: Nuevo}
      fields:  ~
      list:
        title: Localidad Admin
        batch_actions: {}
        object_actions:
          _edit: {label: Editar}
          _delete: {label: Borrar}
      filter:
        class: false
      form: ~
      edit:
        title: Editar Localidad "%%nombre%%"
        actions:
          _save: { label: Guardar }
          _list: { label: Volver }
      new:
        title: Nueva Localidad
        actions:
          _save: {label: Guardar}
          _list: {label: Volver}
          
          
