generator:
  class: sfPropelGenerator
  param:
    model_class:           moneda
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              moneda
    plural:                monedas
    route_prefix:          moneda
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: Nuevo}
      fields:  ~
      list:
        title: Moneda Admin
        display: [numref, moneda, tipocambio]
        batch_actions: {}
        object_actions:
          _edit: {label: Editar}
          _delete: {label: Borrar}
      filter:
        class: false
      form:    ~
      edit:
        title: Editar Moneda "%%moneda%%"
        display: [moneda, tipocambio]
        actions:
          _save: { label: Guardar }
          _list: { label: Volver }
      new:
        title: Nueva Moneda
        display: [moneda, tipocambio]
        actions:
          _save: {label: Guardar}
          _list: {label: Volver}
