generator:
  class: sfPropelGenerator
  param:
    model_class:           tipoGasto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              tipoGasto
    plural:                tipoGastos
    route_prefix:          tipo_gasto
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: Nuevo}
      fields:  ~
      list:
        title: Tipo de Gasto Admin
        batch_actions: {}
        object_actions:
          _edit: {label: Editar}
          _delete: {label: Borrar}
      filter:
         class: false
      form:    ~
      edit:
        title: Editar Tipo Gasto "%%descripcion%%"
        actions:
          _save: { label: Guardar }
          _list: { label: Volver }
      new:
        title: Nueva Localidad
        actions:
          _save: {label: Guardar}
          _list: {label: Volver}
