# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure: on

index:
  credentials: [admin]

all:
  .actions:
    login_module:           sfGuardAuth
    login_action:           signin


    secure_module:          sfGuardAuth
    secure_action:          secure
