<?php

/**
 * Base class that represents a row from the 'moneda' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * 07/28/10 15:21:17
 *
 * @package    lib.model.om
 */
abstract class BaseMoneda extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        MonedaPeer
	 */
	protected static $peer;

	/**
	 * The value for the numref field.
	 * @var        int
	 */
	protected $numref;

	/**
	 * The value for the moneda field.
	 * @var        string
	 */
	protected $moneda;

	/**
	 * The value for the tipocambio field.
	 * @var        string
	 */
	protected $tipocambio;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * @var        array Orden[] Collection to store aggregation of Orden objects.
	 */
	protected $collOrdens;

	/**
	 * @var        Criteria The criteria used to select the current contents of collOrdens.
	 */
	private $lastOrdenCriteria = null;

	/**
	 * @var        array Factura[] Collection to store aggregation of Factura objects.
	 */
	protected $collFacturas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFacturas.
	 */
	private $lastFacturaCriteria = null;

	/**
	 * @var        array Tmpfactura[] Collection to store aggregation of Tmpfactura objects.
	 */
	protected $collTmpfacturas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTmpfacturas.
	 */
	private $lastTmpfacturaCriteria = null;

	/**
	 * @var        array Remito[] Collection to store aggregation of Remito objects.
	 */
	protected $collRemitos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRemitos.
	 */
	private $lastRemitoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'MonedaPeer';

	/**
	 * Get the [numref] column value.
	 * 
	 * @return     int
	 */
	public function getNumref()
	{
		return $this->numref;
	}

	/**
	 * Get the [moneda] column value.
	 * 
	 * @return     string
	 */
	public function getMoneda()
	{
		return $this->moneda;
	}

	/**
	 * Get the [tipocambio] column value.
	 * 
	 * @return     string
	 */
	public function getTipocambio()
	{
		return $this->tipocambio;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of [numref] column.
	 * 
	 * @param      int $v new value
	 * @return     Moneda The current object (for fluent API support)
	 */
	public function setNumref($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->numref !== $v) {
			$this->numref = $v;
			$this->modifiedColumns[] = MonedaPeer::NUMREF;
		}

		return $this;
	} // setNumref()

	/**
	 * Set the value of [moneda] column.
	 * 
	 * @param      string $v new value
	 * @return     Moneda The current object (for fluent API support)
	 */
	public function setMoneda($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->moneda !== $v) {
			$this->moneda = $v;
			$this->modifiedColumns[] = MonedaPeer::MONEDA;
		}

		return $this;
	} // setMoneda()

	/**
	 * Set the value of [tipocambio] column.
	 * 
	 * @param      string $v new value
	 * @return     Moneda The current object (for fluent API support)
	 */
	public function setTipocambio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tipocambio !== $v) {
			$this->tipocambio = $v;
			$this->modifiedColumns[] = MonedaPeer::TIPOCAMBIO;
		}

		return $this;
	} // setTipocambio()

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Moneda The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = MonedaPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->numref = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->moneda = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->tipocambio = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = MonedaPeer::NUM_COLUMNS - MonedaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Moneda object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MonedaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = MonedaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collOrdens = null;
			$this->lastOrdenCriteria = null;

			$this->collFacturas = null;
			$this->lastFacturaCriteria = null;

			$this->collTmpfacturas = null;
			$this->lastTmpfacturaCriteria = null;

			$this->collRemitos = null;
			$this->lastRemitoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MonedaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseMoneda:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				MonedaPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseMoneda:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MonedaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseMoneda:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseMoneda:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				MonedaPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = MonedaPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = MonedaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += MonedaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collOrdens !== null) {
				foreach ($this->collOrdens as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFacturas !== null) {
				foreach ($this->collFacturas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTmpfacturas !== null) {
				foreach ($this->collTmpfacturas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRemitos !== null) {
				foreach ($this->collRemitos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = MonedaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collOrdens !== null) {
					foreach ($this->collOrdens as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFacturas !== null) {
					foreach ($this->collFacturas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTmpfacturas !== null) {
					foreach ($this->collTmpfacturas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRemitos !== null) {
					foreach ($this->collRemitos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MonedaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getNumref();
				break;
			case 1:
				return $this->getMoneda();
				break;
			case 2:
				return $this->getTipocambio();
				break;
			case 3:
				return $this->getId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = MonedaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getNumref(),
			$keys[1] => $this->getMoneda(),
			$keys[2] => $this->getTipocambio(),
			$keys[3] => $this->getId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MonedaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setNumref($value);
				break;
			case 1:
				$this->setMoneda($value);
				break;
			case 2:
				$this->setTipocambio($value);
				break;
			case 3:
				$this->setId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = MonedaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setNumref($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setMoneda($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTipocambio($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setId($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(MonedaPeer::DATABASE_NAME);

		if ($this->isColumnModified(MonedaPeer::NUMREF)) $criteria->add(MonedaPeer::NUMREF, $this->numref);
		if ($this->isColumnModified(MonedaPeer::MONEDA)) $criteria->add(MonedaPeer::MONEDA, $this->moneda);
		if ($this->isColumnModified(MonedaPeer::TIPOCAMBIO)) $criteria->add(MonedaPeer::TIPOCAMBIO, $this->tipocambio);
		if ($this->isColumnModified(MonedaPeer::ID)) $criteria->add(MonedaPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(MonedaPeer::DATABASE_NAME);

		$criteria->add(MonedaPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Moneda (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNumref($this->numref);

		$copyObj->setMoneda($this->moneda);

		$copyObj->setTipocambio($this->tipocambio);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getOrdens() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addOrden($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFacturas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFactura($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTmpfacturas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTmpfactura($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRemitos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRemito($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Moneda Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     MonedaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new MonedaPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collOrdens collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addOrdens()
	 */
	public function clearOrdens()
	{
		$this->collOrdens = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collOrdens collection (array).
	 *
	 * By default this just sets the collOrdens collection to an empty array (like clearcollOrdens());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initOrdens()
	{
		$this->collOrdens = array();
	}

	/**
	 * Gets an array of Orden objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Moneda has previously been saved, it will retrieve
	 * related Ordens from storage. If this Moneda is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Orden[]
	 * @throws     PropelException
	 */
	public function getOrdens($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrdens === null) {
			if ($this->isNew()) {
			   $this->collOrdens = array();
			} else {

				$criteria->add(OrdenPeer::MONEDA, $this->id);

				OrdenPeer::addSelectColumns($criteria);
				$this->collOrdens = OrdenPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(OrdenPeer::MONEDA, $this->id);

				OrdenPeer::addSelectColumns($criteria);
				if (!isset($this->lastOrdenCriteria) || !$this->lastOrdenCriteria->equals($criteria)) {
					$this->collOrdens = OrdenPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastOrdenCriteria = $criteria;
		return $this->collOrdens;
	}

	/**
	 * Returns the number of related Orden objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Orden objects.
	 * @throws     PropelException
	 */
	public function countOrdens(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collOrdens === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(OrdenPeer::MONEDA, $this->id);

				$count = OrdenPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(OrdenPeer::MONEDA, $this->id);

				if (!isset($this->lastOrdenCriteria) || !$this->lastOrdenCriteria->equals($criteria)) {
					$count = OrdenPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collOrdens);
				}
			} else {
				$count = count($this->collOrdens);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Orden object to this object
	 * through the Orden foreign key attribute.
	 *
	 * @param      Orden $l Orden
	 * @return     void
	 * @throws     PropelException
	 */
	public function addOrden(Orden $l)
	{
		if ($this->collOrdens === null) {
			$this->initOrdens();
		}
		if (!in_array($l, $this->collOrdens, true)) { // only add it if the **same** object is not already associated
			array_push($this->collOrdens, $l);
			$l->setMonedaRelatedByMoneda($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Moneda is new, it will return
	 * an empty collection; or if this Moneda has previously
	 * been saved, it will retrieve related Ordens from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Moneda.
	 */
	public function getOrdensJoinClienteRelatedByCliente($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrdens === null) {
			if ($this->isNew()) {
				$this->collOrdens = array();
			} else {

				$criteria->add(OrdenPeer::MONEDA, $this->id);

				$this->collOrdens = OrdenPeer::doSelectJoinClienteRelatedByCliente($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrdenPeer::MONEDA, $this->id);

			if (!isset($this->lastOrdenCriteria) || !$this->lastOrdenCriteria->equals($criteria)) {
				$this->collOrdens = OrdenPeer::doSelectJoinClienteRelatedByCliente($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrdenCriteria = $criteria;

		return $this->collOrdens;
	}

	/**
	 * Clears out the collFacturas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFacturas()
	 */
	public function clearFacturas()
	{
		$this->collFacturas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFacturas collection (array).
	 *
	 * By default this just sets the collFacturas collection to an empty array (like clearcollFacturas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFacturas()
	{
		$this->collFacturas = array();
	}

	/**
	 * Gets an array of Factura objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Moneda has previously been saved, it will retrieve
	 * related Facturas from storage. If this Moneda is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Factura[]
	 * @throws     PropelException
	 */
	public function getFacturas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFacturas === null) {
			if ($this->isNew()) {
			   $this->collFacturas = array();
			} else {

				$criteria->add(FacturaPeer::MONEDA, $this->id);

				FacturaPeer::addSelectColumns($criteria);
				$this->collFacturas = FacturaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FacturaPeer::MONEDA, $this->id);

				FacturaPeer::addSelectColumns($criteria);
				if (!isset($this->lastFacturaCriteria) || !$this->lastFacturaCriteria->equals($criteria)) {
					$this->collFacturas = FacturaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFacturaCriteria = $criteria;
		return $this->collFacturas;
	}

	/**
	 * Returns the number of related Factura objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Factura objects.
	 * @throws     PropelException
	 */
	public function countFacturas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFacturas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FacturaPeer::MONEDA, $this->id);

				$count = FacturaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FacturaPeer::MONEDA, $this->id);

				if (!isset($this->lastFacturaCriteria) || !$this->lastFacturaCriteria->equals($criteria)) {
					$count = FacturaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collFacturas);
				}
			} else {
				$count = count($this->collFacturas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Factura object to this object
	 * through the Factura foreign key attribute.
	 *
	 * @param      Factura $l Factura
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFactura(Factura $l)
	{
		if ($this->collFacturas === null) {
			$this->initFacturas();
		}
		if (!in_array($l, $this->collFacturas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFacturas, $l);
			$l->setMonedaRelatedByMoneda($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Moneda is new, it will return
	 * an empty collection; or if this Moneda has previously
	 * been saved, it will retrieve related Facturas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Moneda.
	 */
	public function getFacturasJoinClienteRelatedByCliente($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFacturas === null) {
			if ($this->isNew()) {
				$this->collFacturas = array();
			} else {

				$criteria->add(FacturaPeer::MONEDA, $this->id);

				$this->collFacturas = FacturaPeer::doSelectJoinClienteRelatedByCliente($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FacturaPeer::MONEDA, $this->id);

			if (!isset($this->lastFacturaCriteria) || !$this->lastFacturaCriteria->equals($criteria)) {
				$this->collFacturas = FacturaPeer::doSelectJoinClienteRelatedByCliente($criteria, $con, $join_behavior);
			}
		}
		$this->lastFacturaCriteria = $criteria;

		return $this->collFacturas;
	}

	/**
	 * Clears out the collTmpfacturas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTmpfacturas()
	 */
	public function clearTmpfacturas()
	{
		$this->collTmpfacturas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTmpfacturas collection (array).
	 *
	 * By default this just sets the collTmpfacturas collection to an empty array (like clearcollTmpfacturas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTmpfacturas()
	{
		$this->collTmpfacturas = array();
	}

	/**
	 * Gets an array of Tmpfactura objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Moneda has previously been saved, it will retrieve
	 * related Tmpfacturas from storage. If this Moneda is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tmpfactura[]
	 * @throws     PropelException
	 */
	public function getTmpfacturas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTmpfacturas === null) {
			if ($this->isNew()) {
			   $this->collTmpfacturas = array();
			} else {

				$criteria->add(TmpfacturaPeer::MONEDA, $this->id);

				TmpfacturaPeer::addSelectColumns($criteria);
				$this->collTmpfacturas = TmpfacturaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TmpfacturaPeer::MONEDA, $this->id);

				TmpfacturaPeer::addSelectColumns($criteria);
				if (!isset($this->lastTmpfacturaCriteria) || !$this->lastTmpfacturaCriteria->equals($criteria)) {
					$this->collTmpfacturas = TmpfacturaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTmpfacturaCriteria = $criteria;
		return $this->collTmpfacturas;
	}

	/**
	 * Returns the number of related Tmpfactura objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tmpfactura objects.
	 * @throws     PropelException
	 */
	public function countTmpfacturas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTmpfacturas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TmpfacturaPeer::MONEDA, $this->id);

				$count = TmpfacturaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TmpfacturaPeer::MONEDA, $this->id);

				if (!isset($this->lastTmpfacturaCriteria) || !$this->lastTmpfacturaCriteria->equals($criteria)) {
					$count = TmpfacturaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTmpfacturas);
				}
			} else {
				$count = count($this->collTmpfacturas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tmpfactura object to this object
	 * through the Tmpfactura foreign key attribute.
	 *
	 * @param      Tmpfactura $l Tmpfactura
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTmpfactura(Tmpfactura $l)
	{
		if ($this->collTmpfacturas === null) {
			$this->initTmpfacturas();
		}
		if (!in_array($l, $this->collTmpfacturas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTmpfacturas, $l);
			$l->setMonedaRelatedByMoneda($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Moneda is new, it will return
	 * an empty collection; or if this Moneda has previously
	 * been saved, it will retrieve related Tmpfacturas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Moneda.
	 */
	public function getTmpfacturasJoinClienteRelatedByCliente($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTmpfacturas === null) {
			if ($this->isNew()) {
				$this->collTmpfacturas = array();
			} else {

				$criteria->add(TmpfacturaPeer::MONEDA, $this->id);

				$this->collTmpfacturas = TmpfacturaPeer::doSelectJoinClienteRelatedByCliente($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TmpfacturaPeer::MONEDA, $this->id);

			if (!isset($this->lastTmpfacturaCriteria) || !$this->lastTmpfacturaCriteria->equals($criteria)) {
				$this->collTmpfacturas = TmpfacturaPeer::doSelectJoinClienteRelatedByCliente($criteria, $con, $join_behavior);
			}
		}
		$this->lastTmpfacturaCriteria = $criteria;

		return $this->collTmpfacturas;
	}

	/**
	 * Clears out the collRemitos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRemitos()
	 */
	public function clearRemitos()
	{
		$this->collRemitos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRemitos collection (array).
	 *
	 * By default this just sets the collRemitos collection to an empty array (like clearcollRemitos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRemitos()
	{
		$this->collRemitos = array();
	}

	/**
	 * Gets an array of Remito objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Moneda has previously been saved, it will retrieve
	 * related Remitos from storage. If this Moneda is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Remito[]
	 * @throws     PropelException
	 */
	public function getRemitos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
			   $this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::MONEDA, $this->id);

				RemitoPeer::addSelectColumns($criteria);
				$this->collRemitos = RemitoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RemitoPeer::MONEDA, $this->id);

				RemitoPeer::addSelectColumns($criteria);
				if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
					$this->collRemitos = RemitoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRemitoCriteria = $criteria;
		return $this->collRemitos;
	}

	/**
	 * Returns the number of related Remito objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Remito objects.
	 * @throws     PropelException
	 */
	public function countRemitos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RemitoPeer::MONEDA, $this->id);

				$count = RemitoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RemitoPeer::MONEDA, $this->id);

				if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
					$count = RemitoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collRemitos);
				}
			} else {
				$count = count($this->collRemitos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Remito object to this object
	 * through the Remito foreign key attribute.
	 *
	 * @param      Remito $l Remito
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRemito(Remito $l)
	{
		if ($this->collRemitos === null) {
			$this->initRemitos();
		}
		if (!in_array($l, $this->collRemitos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRemitos, $l);
			$l->setMonedaRelatedByMoneda($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Moneda is new, it will return
	 * an empty collection; or if this Moneda has previously
	 * been saved, it will retrieve related Remitos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Moneda.
	 */
	public function getRemitosJoinOrden($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::MONEDA, $this->id);

				$this->collRemitos = RemitoPeer::doSelectJoinOrden($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RemitoPeer::MONEDA, $this->id);

			if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
				$this->collRemitos = RemitoPeer::doSelectJoinOrden($criteria, $con, $join_behavior);
			}
		}
		$this->lastRemitoCriteria = $criteria;

		return $this->collRemitos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Moneda is new, it will return
	 * an empty collection; or if this Moneda has previously
	 * been saved, it will retrieve related Remitos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Moneda.
	 */
	public function getRemitosJoinVehiculo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::MONEDA, $this->id);

				$this->collRemitos = RemitoPeer::doSelectJoinVehiculo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RemitoPeer::MONEDA, $this->id);

			if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
				$this->collRemitos = RemitoPeer::doSelectJoinVehiculo($criteria, $con, $join_behavior);
			}
		}
		$this->lastRemitoCriteria = $criteria;

		return $this->collRemitos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Moneda is new, it will return
	 * an empty collection; or if this Moneda has previously
	 * been saved, it will retrieve related Remitos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Moneda.
	 */
	public function getRemitosJoinProveedorRelatedByProveedor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MonedaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRemitos === null) {
			if ($this->isNew()) {
				$this->collRemitos = array();
			} else {

				$criteria->add(RemitoPeer::MONEDA, $this->id);

				$this->collRemitos = RemitoPeer::doSelectJoinProveedorRelatedByProveedor($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RemitoPeer::MONEDA, $this->id);

			if (!isset($this->lastRemitoCriteria) || !$this->lastRemitoCriteria->equals($criteria)) {
				$this->collRemitos = RemitoPeer::doSelectJoinProveedorRelatedByProveedor($criteria, $con, $join_behavior);
			}
		}
		$this->lastRemitoCriteria = $criteria;

		return $this->collRemitos;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collOrdens) {
				foreach ((array) $this->collOrdens as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFacturas) {
				foreach ((array) $this->collFacturas as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTmpfacturas) {
				foreach ((array) $this->collTmpfacturas as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRemitos) {
				foreach ((array) $this->collRemitos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collOrdens = null;
		$this->collFacturas = null;
		$this->collTmpfacturas = null;
		$this->collRemitos = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseMoneda:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseMoneda::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseMoneda
